export interface MenuItem {
  name: string;
  dName: string;
  routeLink: string;
  level: number;
  collapseIconClass: string;
  featureGroup?: string;
  feature?: string;
  action?: string;
  childItem: MenuItem[];
}

export const MENU_CONFIG: MenuItem[] = [
  {
    name: 'Sales Onboarding SmartBoard',
    dName: 'SmartBoard',
    routeLink: '/dashboard/smart-board',
    level: 0,
    collapseIconClass: 'icon-smartboard',
    featureGroup: '',
    feature: '',
    action: '',
    childItem: [],
  },
  {
    name: 'My Profile',
    dName: 'My Profile',
    routeLink: '/dashboard/my-profile',
    level: 0,
    collapseIconClass: 'fa-solid fa-user',
    featureGroup: 'Manage My Profile',
    feature: 'MyProfile',
    action: 'View',
    childItem: [],
  },
  {
    name: 'My Message',
    dName: 'Inbox',
    routeLink: '/dashboard/my-message/message',
    level: 0,
    collapseIconClass: 'fa-solid fa-comment',
    featureGroup: 'Manage My Message',
    feature: 'My Message',
    action: 'View',
    childItem: [],
  },
  {
    name: 'Readiness',
    dName: 'Readiness',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'fa-solid fa-chart-simple',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Manage Requirements',
        dName: 'Manage Requirements',
        routeLink: '/dashboard/requirement/manage-requirements',
        level: 0,
        collapseIconClass: 'ti ti-user-edit',
        featureGroup: 'Manage Readiness',
        feature: 'Manage Requirements',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Create Requirements',
        dName: 'Create Requirements',
        routeLink: '/dashboard/requirement/create-requirements',
        level: 0,
        collapseIconClass: 'ti ti-user-plus',
        featureGroup: 'Manage Readiness',
        feature: 'Create Requirements',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Import Requirements',
        dName: 'Import Requirements',
        routeLink: '/dashboard/requirement/import-requirements',
        level: 0,
        collapseIconClass: 'ti ti-user-plus',
        featureGroup: 'Manage Readiness',
        feature: 'Import Requirements',
        action: 'Import',
        childItem: [],
      },
    ],
  },
  {
    name: 'Chats',
    dName: 'Chats',
    routeLink: '/dashboard/chats/',
    level: 0,
    collapseIconClass: 'ti ti-user-cog',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [],
  },
  {
    name: 'Permissions',
    dName: 'Permissions',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'ti ti-accessible',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Manage Permissions',
        dName: 'Manage Permissions',
        routeLink: '/dashboard/permission',
        level: 0,
        collapseIconClass: 'ti ti-key',
        featureGroup: 'Manage Permission',
        feature: 'Permission Management',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Manage Approvals',
        dName: 'Manage System Approvals',
        routeLink: '/dashboard/permission/manageApprovals',
        level: 0,
        collapseIconClass: 'ti ti-check',
        featureGroup: 'Manage Permission',
        feature: 'Approval Management',
        action: 'View',
        childItem: [],
      },
    ],
  },
  {
    name: 'Scheduling',
    dName: 'Scheduling',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'ti ti-calendar-check',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Slots',
        dName: 'Slots',
        routeLink: '/dashboard/scheduling',
        level: 0,
        collapseIconClass: 'ti ti-user-edit',
        featureGroup: 'Manage Scheduling',
        feature: 'Slots',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Schedule',
        dName: 'Schedule',
        routeLink: '/dashboard/scheduling/schedule',
        level: 0,
        collapseIconClass: 'fa-solid fa-calendar',
        featureGroup: 'Manage Scheduling',
        feature: 'Schedule',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Appointments',
        dName: 'Appointments',
        routeLink: '/dashboard/scheduling/appointments',
        level: 0,
        collapseIconClass: 'fa-solid fa-calendar-day',
        featureGroup: 'Manage Scheduling',
        feature: 'Appointments',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Create Appointments',
        dName: 'Create Appointments',
        routeLink: '/dashboard/scheduling/create-appointments',
        level: 0,
        collapseIconClass: 'fa-solid fa-calendar-plus',
        featureGroup: 'Manage Scheduling',
        feature: 'Appointments',
        action: 'Add',
        childItem: [],
      },
    ],
  },
  {
    name: 'Communication',
    dName: 'Communication',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'fa-solid fa-tower-cell',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Checklists',
        dName: 'Checklists',
        routeLink: '/dashboard/communication/',
        level: 0,
        collapseIconClass: 'fa-solid fa-list-check',
        featureGroup: 'Manage Communication',
        feature: 'Checklists',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Surveys',
        dName: 'Surveys',
        routeLink: '/dashboard/communication/surveys',
        level: 0,
        collapseIconClass: 'fa-solid fa-clipboard-list',
        featureGroup: 'Manage Communication',
        feature: 'Surveys',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Announcements',
        dName: 'Announcements',
        routeLink: '/dashboard/communication/announcements',
        level: 0,
        collapseIconClass: 'fa-solid fa-bullhorn',
        featureGroup: 'Manage Communication',
        feature: 'Announcements',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Nudge Groups',
        dName: 'Nudge Groups',
        routeLink: '/dashboard/communication/nudge-groups',
        level: 0,
        collapseIconClass: 'fa-solid fa-users-gear',
        featureGroup: 'Manage Communication',
        feature: 'Nudge Groups',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Checklist Message',
        dName: 'Checklist Message',
        routeLink: '/dashboard/communication/create-checklist',
        level: 0,
        collapseIconClass: 'ti ti-brand-messenger',
        featureGroup: 'Manage Communication',
        feature: 'Checklists',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Survey Message',
        dName: 'Survey Message',
        routeLink: '/dashboard/communication/survey-message',
        level: 0,
        collapseIconClass: 'ti ti-brand-messenger',
        featureGroup: 'Manage Communication',
        feature: 'Surveys',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Create Announcement',
        dName: 'Create Announcement',
        routeLink: '/dashboard/communication/create-announcement',
        level: 0,
        collapseIconClass: 'ti ti-brand-messenger',
        featureGroup: 'Manage Communication',
        feature: 'Announcements',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Create Nudge Group',
        dName: 'Create Nudge Group',
        routeLink: '/dashboard/communication/create-nudge-group',
        level: 0,
        collapseIconClass: 'ti ti-brand-messenger',
        featureGroup: 'Manage Communication',
        feature: 'Nudge Groups',
        action: 'View',
        childItem: [],
      },
    ],
  },
  {
    name: 'Data Loader',
    dName: 'Data Loader',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'ti ti-database-import',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Alpha Roster',
        dName: 'Alpha Roster',
        routeLink: '/dashboard/data-loader',
        level: 0,
        collapseIconClass: 'fa-solid fa-table',
        featureGroup: 'Manage Data Loader',
        feature: 'Alpha Roaster',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Requirements',
        dName: 'Requirements',
        routeLink: '/dashboard/data-loader/requirements',
        level: 0,
        collapseIconClass: 'fa-solid fa-star',
        featureGroup: 'Manage Data Loader',
        feature: 'Requirements',
        action: 'View',
        childItem: [],
      },
    ],
  },

  {
    name: 'Users & Groups',
    dName: 'Users & Groups',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'ti ti-users',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Manage Airmen',
        dName: 'Manage Airmen',
        routeLink: '/dashboard/userAndgroup',
        level: 0,
        collapseIconClass: 'ti ti-user-edit',
        featureGroup: 'Manage User and Groups',
        feature: 'Manage Airman',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Create',
        dName: 'Create Airman',
        routeLink: '/dashboard/userAndgroup/createAirman',
        level: 0,
        collapseIconClass: 'ti ti-user-plus',
        featureGroup: 'Manage User and Groups',
        feature: 'Create Airman',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Import Airmen',
        dName: 'Import Airmen',
        routeLink: '/dashboard/userAndgroup/importAirman',
        level: 0,
        collapseIconClass: 'ti ti-user-plus',
        featureGroup: 'Manage User and Groups',
        feature: 'Create Airman',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Roles',
        dName: 'Roles',
        routeLink: '/dashboard/userAndgroup/roles',
        level: 0,
        collapseIconClass: 'fa-solid fa-image-portrait',
        featureGroup: 'Manage User and Groups',
        feature: 'Roles',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Command Activities',
        dName: 'Command Activities',
        routeLink: '/dashboard/userAndgroup/command-activites',
        level: 0,
        collapseIconClass: 'fa-solid fa-users-rectangle',
        featureGroup: 'Manage User and Groups',
        feature: 'Command Activities',
        action: 'Add',
        childItem: [],
      },
      {
        name: 'Squadrons',
        dName: 'Squadrons',
        routeLink: '/dashboard/userAndgroup/squadrons',
        level: 0,
        collapseIconClass: 'fa-solid fa-plane',
        featureGroup: 'Manage User and Groups',
        feature: 'Squadrons',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Flights',
        dName: 'Flights',
        routeLink: '/dashboard/userAndgroup/flight',
        level: 0,
        collapseIconClass: 'fa-solid fa-users-line',
        featureGroup: 'Manage User and Groups',
        feature: 'Flights',
        action: 'View',
        childItem: [],
      },
    ],
  },
  {
    name: 'Settings',
    dName: 'Settings',
    routeLink: ' ',
    level: 0,
    collapseIconClass: 'fa-solid fa-gear',
    featureGroup: ' ',
    feature: ' ',
    action: ' ',
    childItem: [
      {
        name: 'Surveys',
        dName: 'Surveys',
        routeLink: '/dashboard/settings/survey',
        level: 0,
        collapseIconClass: 'fa-solid fa-clipboard-list',
        featureGroup: 'Manage Settings',
        feature: 'Survey Management',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Checklists',
        dName: 'Checklists',
        routeLink: '/dashboard/settings/manage-checklists',
        level: 0,
        collapseIconClass: 'fa-solid fa-list-check',
        featureGroup: 'Manage Settings',
        feature: 'Survey Management',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Specialty',
        dName: 'Specialty',
        routeLink: '/dashboard/settings/speciality',
        level: 0,
        collapseIconClass: 'fa-solid fa-star-of-life',
        featureGroup: 'Manage Settings',
        feature: 'Specialty',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Category',
        dName: 'Category',
        routeLink: '/dashboard/settings/category',
        level: 0,
        collapseIconClass: 'fa-solid fa-layer-group',
        featureGroup: 'Manage Settings',
        feature: 'Category',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Sub Category',
        dName: 'Sub Category',
        routeLink: '/dashboard/settings/sub-category',
        level: 0,
        collapseIconClass: 'fa-solid fa-table-columns',
        featureGroup: 'Manage Settings',
        feature: 'Sub Category',
        action: 'View',
        childItem: [],
      },
      {
        name: 'Requirement Weight',
        dName: 'Requirement Weight',
        routeLink: '/dashboard/settings/requirement-weight',
        level: 0,
        collapseIconClass: 'ti ti-user-plus',
        featureGroup: 'Manage Settings',
        feature: 'Requirement Weighting',
        action: 'View',
        childItem: [],
      },
    ],
  },
];
